---
abstract: 'IP string to number and back'
author:
  - 'Tamir Lousky <tlousky@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-IPAddress-Minimal
provides:
  Net::IPAddress::Minimal:
    file: lib/Net/IPAddress/Minimal.pm
    version: 0.02
requires:
  Exporter: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
